### ISSUE TITLE
OPAM support

### ISSUE THREAD

**Issue by erikmd** [coq/ltac2#105]
Hi @ppedrot,
With @proux01, we plan to prepare an opam package of our validsdp library in a couple of days (when I'll have finished the migration to Ltac2) to support Coq 8.7, 8.8, 8.9.

Currently the only versions available in released+extra-dev are:
```
$ opam show coq-ltac2
name         coq-ltac2
all-versions 0.1-8.7  8.7.dev  dev
```

Would you be OK to make a new release of Ltac2 for Coq 8.7/8.8/8.9?
Otherwise (if you think it's not relevant for the moment given the development roadmap), would you agree to create opam packages in `extra-dev` to map branches `v8.7`, `v8.8`, `v8.9` to these versions of `coq`?
- `{(>= "8.7" & < "8.8~")}`
- `{(>= "8.8" & < "8.9~")}`
- `{(>= "8.9" & < "8.10~")}`

If it helps, I can open a corresponding PR in `opam-coq-archive / extra-dev`

(*Edit: sorry, I mis-clicked and my message was sent too early*)

**Comment by Zimmi48** [comment]
@erikmd It would probably make sense to proceed and create the missing opam packages without waiting for @ppedrot. Sigh! It turns out that the last commit compatible with 8.7 (from the v8.7 branch) is the one tagged v8.7-0.1, the last commit compatible with 8.8 (from the v8.8 branch) is the one tagged 0.1, the last commit compatible with 8.9 (from the v8.9 branch) is a69551a49543b22a7d4e6a2484356b56bd05068e (no tag), and the last commit compatible with 8.10 is 72ab28cc8c497a9a87647ab2c329b7e3ff40fa38 (no tag, no branch).

**Comment by Zimmi48** [comment]
Actually, I proceeded to create a v8.10 branch from this commit.

@ppedrot The master branch should be updated to remove all code and redirect to the Coq repository.

**Comment by erikmd** [comment]
@Zimmi48 thanks for your compatibility analysis and feedback!

I'll be able to create these opam packages in **extra-dev** to track the development branches of Ltac2.

But meanwhile, let me ask something more: would you be OK to add these missing tags
(e.g. `v8.9-0.2` => [`a69551a`](https://github.com/coq/ltac2/commit/a69551a49543b22a7d4e6a2484356b56bd05068e), `v8.10-0.3` => [`72ab28c`](https://github.com/coq/ltac2/commit/72ab28cc8c497a9a87647ab2c329b7e3ff40fa38)) to the coq/ltac2 repo?
that'd be really great, so @proux01 and I will be able to rely on in directly *via* the coq **released** repo…

Cc @ppedrot @Zimmi48

**Comment by Zimmi48** [comment]
Since @ppedrot does not answer I might intervene and put the tag myself. But let's talk about this next week since we'll all be in the same place.

**Comment by erikmd** [comment]
@Zimmi48 OK (unfortunately I won't be able to attend the workshop, anyway thanks for your comment!)

**Comment by Zimmi48** [comment]
The tags are now put. I am going to update the README in master to explain that this repository is for storing the old branches, but is not maintained anymore.
